#index:
#    path: /
#    controller: App\Controller\DefaultController::index
ajax_get_appointments:
  path: /ajax/get/appointments
  controller: App\Controller\AjaxGetAppointmentsController::getAppoint
  methods: [ get,post ]