version: '3.9'

services:
  test-php:
    container_name: testPhp
    build:
      context: ../.
      dockerfile: Dockerfile.dev
    volumes:
      - ../../:/var/www
      - ../s6script/cont-init.d:/etc/cont-init.d
      - ../s6script/cont-finish.d:/etc/cont-finish.d
    ports:
      - 8280:8080
      - 3100:3000

  test-nginx:
    image: nginx:latest
    container_name: test-nginx
    ports:
      - 443:443
    volumes:
      - ../../:/var/www
      - ../../certs:/etc/nginx/certs
      - ../Configs/Dev/nginx.conf:/etc/nginx/conf.d/default.conf

  test-postgres:
    image: library/postgres:10.14
    container_name: test-postgres
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "root"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 54320:5432
    volumes:
      - test_postgres_data10:/var/lib/postgresql/data10

volumes:
  test_postgres_data10: { }
